# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

run_leverage_cycles_model <- function(out, double_params, stochastic, seed) {
    .Call('leverageCycles_run_leverage_cycles_model', PACKAGE = 'leverageCycles', out, double_params, stochastic, seed)
}

