// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// run_leverage_cycles_model
NumericMatrix run_leverage_cycles_model(NumericMatrix out, NumericVector double_params, int stochastic, int seed);
RcppExport SEXP leverageCycles_run_leverage_cycles_model(SEXP outSEXP, SEXP double_paramsSEXP, SEXP stochasticSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type out(outSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type double_params(double_paramsSEXP);
    Rcpp::traits::input_parameter< int >::type stochastic(stochasticSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    __result = Rcpp::wrap(run_leverage_cycles_model(out, double_params, stochastic, seed));
    return __result;
END_RCPP
}
